logging:
  level:
    root: info
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cardb
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  data:
    rest:
      basePath: /api

  output:
    ansi:
      enabled: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
